import { Theme } from '@radix-ui/themes'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import Sidebar from './components/Sidebar';
import { Providers } from '@/app/provider' // ← Importa aquí


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
/* BACKGROUND COLOR =#F9F9F9"*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body style={{backgroundColor:'#F9F9F9'}}>

        <Providers>
          <Theme style={{ backgroundColor: "#F9F9F9" }}>
            <NavBar />

            {children}

          </Theme>
        </Providers>
      </body>
    </html>
  );
}
